Unsorted_segment_mean() is used to find the mean of segments.

In [1]:
# importing the library
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

# unsorted_segment_sum

In [3]:
data = tf.constant([0.2, 0.1, 0.5, 0.7, 0.8])
segment_ids = tf.constant([0, 0, 1, 2, 2])

In [4]:
res = tf.math.unsorted_segment_sum(data, segment_ids, 3)
print(res)

tf.Tensor([0.3 0.5 1.5], shape=(3,), dtype=float32)


In [5]:
res = tf.math.unsorted_segment_sum(data, segment_ids, 2)
print(res)

tf.Tensor([0.3 0.5], shape=(2,), dtype=float32)


In [6]:
res = tf.math.unsorted_segment_sum(data, segment_ids, 1)
print(res)

tf.Tensor([0.3], shape=(1,), dtype=float32)


In [7]:
res = tf.math.unsorted_segment_sum(data, segment_ids, 4)
print(res)

tf.Tensor([0.3 0.5 1.5 0. ], shape=(4,), dtype=float32)


In [8]:
res = tf.math.unsorted_segment_sum(tf.constant([[0.2, 0.1, 0.5, 0.7, 0.8],
                                     [0.2, 0.2, 0.5, 0.7, 0.8]]),
                        tf.constant([[0, 0, 1, 2, 2],
                                     [0, 0, 1, 2, 2]]), 3)
print(res)

tf.Tensor([0.7 1.  3. ], shape=(3,), dtype=float32)


# unsorted_segment_mean

In [9]:
# Initializing the input tensor
data = tf.constant([1, 2, 3])
segment_ids = tf.constant([2, 2, 2])
  
# Printing the input tensor
print('data: ', data)
print('segment_ids: ', segment_ids)
  
# Calculating result
res = tf.math.unsorted_segment_mean(data, segment_ids, tf.constant(3))
  
# Printing the result
print('Result: ', res)

data:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
segment_ids:  tf.Tensor([2 2 2], shape=(3,), dtype=int32)
Result:  tf.Tensor([0. 0. 2.], shape=(3,), dtype=float64)


In [10]:
# Initializing the input tensor
data = tf.constant([[1, 2, 3], [4, 5, 6]])
segment_ids = tf.constant([1, 0])
  
# Printing the input tensor
print('data: ', data)
print('segment_ids: ', segment_ids)
  
# Calculating result
res = tf.math.unsorted_segment_mean(data, segment_ids, tf.constant(2))
  
# Printing the result
print('Result: ', res)

data:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
segment_ids:  tf.Tensor([1 0], shape=(2,), dtype=int32)
Result:  tf.Tensor(
[[4. 5. 6.]
 [1. 2. 3.]], shape=(2, 3), dtype=float64)


In [11]:
# Initializing the input tensor
data = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
segment_ids = tf.constant([0, 2,  2])
# segment_ids 는 axis 의 index 와 같아야 함?  idx는 모두 부여해야하므로.

# Printing the input tensor
print('data: ', data)
print('segment_ids: ', segment_ids)
  
# Calculating result
res = tf.math.unsorted_segment_mean(data, segment_ids, num_segments = 3)
  
# Printing the result
print('Result: ', res)

data:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
segment_ids:  tf.Tensor([0 2 2], shape=(3,), dtype=int32)
Result:  tf.Tensor(
[[1.  2.  3. ]
 [0.  0.  0. ]
 [5.5 6.5 7.5]], shape=(3, 3), dtype=float64)


### References

https://stackoverflow.com/q/43210033

https://www.geeksforgeeks.org/python-tensorflow-math-unsorted_segment_mean/
